[project]
title = "Preswald Project"
version = "0.1.0"
port = 8501
slug = "my-app-492180"  
entrypoint = "hello.py"    

[branding]
name = "Project Basecamp"
logo = "images/logoH.png"
favicon = "images/faviconH.ico"
primaryColor = "#F89613"

[data.sample_csv]
type = "csv"
path = "data/sample.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"